export const dataTest = {
    data: [
      {
        id: 1,
        name: "Gregg Brakus",
        title: "Gregg Brakus",
        url: "aaaaaaaa",
        likeCount: 10,
        reactVideo: null,
        createdAt: 1681016264415,
      },
      {
        id: 2,
        name: "Belarus",
        title: "Gregg Brakus",
        url: "aaaaaaaa",
        likeCount: 10,
        reactVideo: false,
        createdAt: 1681016264415,
      },
      {
        id: 3,
        name: "American Russia",
        title: "Gregg Brakus",
        url: "aaaaaaaa",
        likeCount: 10,
        reactVideo: true,
        createdAt: 1681016264415,
      },
      {
        id: 4,
        name: "Billaird 18",
        title: "Gregg Brakus",
        url: "aaaaaaaa",
        likeCount: 10,
        reactVideo: true,
        createdAt: 1681016264415,
      },
    ],
    pagination: {
      _page: 1,
      _limit: 10,
      _totalRows: 10,
    },
  };